In [61]:
import pandas as pd
import numpy as np

In [62]:
data = {
    "Name": ['Iyynes', 'Adithya', 'Deepa', 'Muthu', 'Sri', 'Gobika', np.nan, 'Iyynes'],
    "Age": [20, 15, 18, np.nan, 19, 18, np.nan, 20],
    "Department": ['Full-stack', np.nan, 'UI/UX', 'Backend', 'Frontend', 'AI', np.nan, 'Full-stack'],
    "Salary": [90000, 70000, 80000, 90000, np.nan, 55000, np.nan, 90000]
}

In [63]:
df = pd.DataFrame(data)
df['Promoted Salary'] = df['Salary'] + 15000
print(df)

      Name   Age  Department   Salary  Promoted Salary
0   Iyynes  20.0  Full-stack  90000.0         105000.0
1  Adithya  15.0         NaN  70000.0          85000.0
2    Deepa  18.0       UI/UX  80000.0          95000.0
3    Muthu   NaN     Backend  90000.0         105000.0
4      Sri  19.0    Frontend      NaN              NaN
5   Gobika  18.0          AI  55000.0          70000.0
6      NaN   NaN         NaN      NaN              NaN
7   Iyynes  20.0  Full-stack  90000.0         105000.0

In [64]:
df['Promoted Salary'] = df['Promoted Salary'].apply(lambda x: x/10 if x > 75000 else x/5)
df

      Name   Age  Department   Salary  Promoted Salary
0   Iyynes  20.0  Full-stack  90000.0          10500.0
1  Adithya  15.0         NaN  70000.0           8500.0
2    Deepa  18.0       UI/UX  80000.0           9500.0
3    Muthu   NaN     Backend  90000.0          10500.0
4      Sri  19.0    Frontend      NaN              NaN
5   Gobika  18.0          AI  55000.0          14000.0
6      NaN   NaN         NaN      NaN              NaN
7   Iyynes  20.0  Full-stack  90000.0          10500.0

In [65]:
df.drop_duplicates(inplace=True)
df

      Name   Age  Department   Salary  Promoted Salary
0   Iyynes  20.0  Full-stack  90000.0          10500.0
1  Adithya  15.0         NaN  70000.0           8500.0
2    Deepa  18.0       UI/UX  80000.0           9500.0
3    Muthu   NaN     Backend  90000.0          10500.0
4      Sri  19.0    Frontend      NaN              NaN
5   Gobika  18.0          AI  55000.0          14000.0
6      NaN   NaN         NaN      NaN              NaN

In [66]:
df.dropna(how='all', inplace=True)
df

      Name   Age  Department   Salary  Promoted Salary
0   Iyynes  20.0  Full-stack  90000.0          10500.0
1  Adithya  15.0         NaN  70000.0           8500.0
2    Deepa  18.0       UI/UX  80000.0           9500.0
3    Muthu   NaN     Backend  90000.0          10500.0
4      Sri  19.0    Frontend      NaN              NaN
5   Gobika  18.0          AI  55000.0          14000.0

In [67]:
# replace a particular value with another

print("Original dataset\n", df['Name'], sep='\n')
print("\n dataset with replaced value \n",df['Name'].replace("Sri", "Srinidhi"))

Original dataset

0     Iyynes
1    Adithya
2      Deepa
3      Muthu
4        Sri
5     Gobika
Name: Name, dtype: object

 dataset with replaced value
 0      Iyynes
1     Adithya
2       Deepa
3       Muthu
4    Srinidhi
5      Gobika
Name: Name, dtype: object

In [68]:
# to make the change permanent:
df['Name'] = df['Name'].replace("Srinidhi", "unknown")
df

      Name   Age  Department   Salary  Promoted Salary
0   Iyynes  20.0  Full-stack  90000.0          10500.0
1  Adithya  15.0         NaN  70000.0           8500.0
2    Deepa  18.0       UI/UX  80000.0           9500.0
3    Muthu   NaN     Backend  90000.0          10500.0
4      Sri  19.0    Frontend      NaN              NaN
5   Gobika  18.0          AI  55000.0          14000.0

In [69]:
# apply and lambda
def multiplying_age(x):
    return x*2
df['Age'] = df['Age'].apply(multiplying_age)

In [70]:
df['Age'].ffill(inplace=True)
df

C:\Users\pdee5\AppData\Local\Temp\ipykernel_4456\2679131846.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].ffill(inplace=True)

      Name   Age  Department   Salary  Promoted Salary
0   Iyynes  40.0  Full-stack  90000.0          10500.0
1  Adithya  30.0         NaN  70000.0           8500.0
2    Deepa  36.0       UI/UX  80000.0           9500.0
3    Muthu  36.0     Backend  90000.0          10500.0
4      Sri  38.0    Frontend      NaN              NaN
5   Gobika  36.0          AI  55000.0          14000.0

In [71]:
df['Age'] = df['Age'].apply(lambda x: x/2)
df

      Name   Age  Department   Salary  Promoted Salary
0   Iyynes  20.0  Full-stack  90000.0          10500.0
1  Adithya  15.0         NaN  70000.0           8500.0
2    Deepa  18.0       UI/UX  80000.0           9500.0
3    Muthu  18.0     Backend  90000.0          10500.0
4      Sri  19.0    Frontend      NaN              NaN
5   Gobika  18.0          AI  55000.0          14000.0